input {
  tcp {
    port => 5000
    codec => json_lines
  }
  udp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [service_name] {
    mutate {
      add_field => { "[@metadata][index_prefix]" => "%{service_name}" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][index_prefix]" => "unknown-service" }
    }
  }

  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
    remove_field => ["timestamp"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "taskmanager-%{[@metadata][index_prefix]}-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
